services:
  - type: web
    name: amazon-eu-comparator
    env: node
    plan: free
    region: frankfurt
    buildCommand: npm install --prefer-offline --no-audit
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "false"
      - key: PUPPETEER_CACHE_DIR
        value: "/tmp/.puppeteer_cache"
      - key: NODE_ENV
        value: "production"
